http://http://20.166.216.190/bbm/order/
Content-Type: application/json

{
  "Date": "2022-12-07",
  "Items": [
    {
      "ProductCode": "rockiecookie",
      "Quantity": 1
    },
    {
      "ProductCode": "bussola8",
      "Quantity": 2
    }
  ]
}