#This is for storing whatever comes through the sample.microservice.service2 controller. Set up with Azure Cosmos NoSQL Database 
#with the collection called shippingstate
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shippingstore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    secretKeyRef:
      name: url
      key: url

  - name: masterKey
    secretKeyRef:
      name: masterKey
      key: masterKey

  - name: database
    value: state
  - name: collection
    value: shippingstate
auth:
  secretStore: localsecretstore