#This is for declarative subscribing to a topic on the configured pub/sub bus. Currently Azure Service Bus from pubsub.yaml.
#Listens on the topic on_order_stored with the pubsubname of commonpubsub and is handled on the route /checkout. The subscribing service is shipping-service
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: orders
spec:
  topic: on_order_stored
  route: /checkout
  pubsubname: commonpubsub
scopes:
  - shipping-service
